lab3: main

main:
	@g++ main.cpp cpp/GradeRatesByCategory.cpp headers/GradeRatesByCategory.h cpp/CourseReporter.cpp headers/CourseReporter.h cpp/TypedPassRate.cpp headers/TypedPassRate.h cpp/UserControl.cpp headers/UserControl.h cpp/OutputManager.cpp headers/OutputManager.h
